apiVersion: v1
kind: Pod
metadata:
  name: "app"
  namespace: development
  labels:
    app: "app"
    app-version: "v1"
spec:
  containers:
  - name: app
    image: "3raya/sql-web-admin:0.2"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: DB_NAME
      value: "postgres"
    
    - name: DB_USER
      value: "postgres"

    - name: DB_PASSWORD
      value: "postgres"
    
    - name: HOST
      value: "db-service"

    ports:
    - containerPort:  5000
      name:  http

