apiVersion: v1
kind: Pod
metadata:
  name: "db"
  namespace: development
  labels:
    app: "backend"
    db-version: "latest"
    app-version: "v1"
spec:
  volumes:
   - name: migration
     configMap:
       name: db-migration

  containers:
  - name: db
    image: "postgres"

    volumeMounts:
     - name: migration
       mountPath:  /docker-entrypoint-initdb.d

    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: app-credentials
          key: db-user
    - name: POSTGRES_PASSWORD
      valueFrom:
       secretKeyRef:
         name: app-credentials
         key: db-password
    ports:
    - containerPort:  5432
      name:  http
